#!/usr/bin/env bash
# verify-state.sh — produce supervisor/system/verified-state.md from PRIMARY sources only.
#
# Output format is stable so sessions, ticks, and the principal can diff it across runs.
# Never reads tick-generated narrative; only queries the host and the repos.
#
# Usage:
#   scripts/lib/verify-state.sh            # writes to system/verified-state.md
#   scripts/lib/verify-state.sh --stdout   # prints to stdout only
#
# This script MUST remain fast (<10s) so sessions actually run it.
set -euo pipefail

WORKSPACE=/opt/workspace
SUPERVISOR=$WORKSPACE/supervisor
RUNTIME=$WORKSPACE/runtime
OUT=$SUPERVISOR/system/verified-state.md

STDOUT=0
if [[ "${1:-}" == "--stdout" ]]; then STDOUT=1; fi

TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
NOW_EPOCH=$(date -u +%s)
STALE_THRESHOLD_SECONDS=900

warn_if_existing_verified_state_stale() {
  [[ -f "$OUT" ]] || return 0
  local generated_ts generated_epoch age
  generated_ts=$(grep '^generated:' "$OUT" 2>/dev/null | head -1 | awk '{print $2}')
  [[ -n "$generated_ts" ]] || return 0
  generated_epoch=$(date -u -d "$generated_ts" +%s 2>/dev/null || echo 0)
  [[ "$generated_epoch" =~ ^[0-9]+$ ]] || generated_epoch=0
  (( generated_epoch > 0 )) || return 0
  age=$(( NOW_EPOCH - generated_epoch ))
  if (( age > STALE_THRESHOLD_SECONDS )); then
    printf 'WARN: verified-state.md content is %dm stale (generated: %s)\n' \
      $(( age / 60 )) "$generated_ts" >&2
  fi
}

warn_if_existing_verified_state_stale

q() { # quiet-fail command substitution
  eval "$@" 2>/dev/null || echo "(unavailable)"
}

inbox_actionable_count() {
  find "$SUPERVISOR/handoffs/INBOX" -maxdepth 1 -type f \
    ! -name '.gitkeep' \
    ! -name 'session-summary-*.md' 2>/dev/null | wc -l
}

inbox_actionable_items() {
  find "$SUPERVISOR/handoffs/INBOX" -maxdepth 1 -type f \
    ! -name '.gitkeep' \
    ! -name 'session-summary-*.md' -printf '%f\n' 2>/dev/null | sort | head -10 | sed 's/^/  - /'
}

general_actionable_count() {
  find "$RUNTIME/.handoff" -maxdepth 1 -type f -name 'general-*.md' \
    ! -name 'general-*-complete-*.md' \
    ! -name 'general-*-tick-complete-*.md' \
    ! -name 'general-cowork-loop-closed-confirmation-*.md' 2>/dev/null | wc -l
}

supervisor_dirty_state() {
  local dirty
  dirty=$(cd "$SUPERVISOR" && git status --short -- . ':!system/verified-state.md' 2>/dev/null || true)
  [[ -z "$dirty" ]] && echo "clean" || echo "DIRTY — run git status"
}

http() {
  local code
  code=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "$1" 2>/dev/null)
  [[ -z "$code" || "$code" == "000" ]] && code="000"
  printf "%s" "$code"
}

kernel_pending() {
  local running newest
  running=$(uname -r)
  newest=$(ls /boot/vmlinuz-* 2>/dev/null | sed 's|/boot/vmlinuz-||' | sort -V | tail -1)
  if [[ "$running" == "$newest" ]]; then
    echo "no"
  else
    echo "YES — running $running, newest installed $newest"
  fi
}

svc() {
  local unit=$1
  local state
  state=$(systemctl is-active "$unit" 2>/dev/null || echo "missing")
  local since
  since=$(systemctl show "$unit" -p ActiveEnterTimestamp --value 2>/dev/null || echo "")
  printf "%-40s %-10s since %s\n" "$unit" "$state" "${since:-(n/a)}"
}

BUF=$(mktemp)
exec 3>"$BUF"

cat >&3 <<HEADER
---
name: Verified system state
description: Primary-source snapshot of workspace state. Generated by scripts/lib/verify-state.sh. Never hand-edit — re-run the script. This is the source of truth for status claims; active-issues.md is curated pressure, not state.
updated: $(date -u +%Y-%m-%d)
generated: $TS
---

# Verified system state

This file is generated. Do not edit by hand. Any claim in principal-facing
output about kernel, deploys, services, public URLs, paid services, or
pending credentials MUST cite a line from this file (not from
\`active-issues.md\`, which is curated pressure).

## Host

- **Kernel running**: $(q uname -r)
- **Kernels installed**: $(ls /boot/vmlinuz-* 2>/dev/null | sed 's|/boot/vmlinuz-||' | paste -sd ', ')
- **Reboot pending**: $(kernel_pending)
- **Uptime**: $(uptime -p 2>/dev/null || echo "(unavailable)")
- **Disk /**: $(df -h / | awk 'NR==2 {print $3" used / "$2" total ("$5" full)"}')
- **Memory**: $(free -h | awk 'NR==2 {print $3" used / "$2" total"}')

## Services (workspace scope)

\`\`\`
$(svc cloudflared.service)
$(svc command.service)
$(svc launchpad-lint.service)
$(svc preflight.service)
$(svc preflight-watcher.service)
$(svc workspace-session@atlas.service)
$(svc workspace-session@command.service)
$(svc workspace-session@context-repo.service)
$(svc workspace-session@general.service)
$(svc workspace-session@skillfoundry.service)
\`\`\`

## Public URLs (live HTTP check)

HEADER

for url in \
  https://skillfoundry.synaplex.ai/products/launchpad-lint/ \
  https://skillfoundry.synaplex.ai/ \
  https://command.synaplex.ai/ \
  https://mentor.synaplex.ai/ \
  https://api.synaplex.ai/; do
  code=$(http "$url")
  echo "- \`$code\` $url" >&3
done

cat >&3 <<PAID

## Paid services — quick register

| Service | Purpose | Live state | Credentials path |
|---|---|---|---|
| Hetzner CPX31 (5.78.185.6) | Workspace host | uptime $(uptime -p 2>/dev/null | sed 's/up //') | SSH key on principal's local |
| Cloudflare | DNS (synaplex.ai, migrating from Namecheap), tunnel, Pages (planned) | $(systemctl is-active cloudflared 2>/dev/null) | \`$RUNTIME/.secrets/cloudflare_api_token\` $([[ -f $RUNTIME/.secrets/cloudflare_api_token ]] && echo "(present)" || echo "(MISSING — rotation pending per handoffs/INBOX)") |
| Namecheap | Legacy registrar for synaplex.ai | migrating out | principal login |
| Render | launchpad-lint → agenticmarket MCP marketplace | live per principal 2026-04-18T12:47Z | principal login |
| Anthropic API | Claude harness + SDK calls | active | host env |
| OpenAI / Codex | Adversarial review via \`adversarial-review.sh\` | available | host env |

Full register: \`supervisor/system/paid-services.md\`.

## Governance

- **Supervisor HEAD**: $(cd $SUPERVISOR && git rev-parse --short HEAD) — $(cd $SUPERVISOR && git log -1 --pretty=%s)
- **Dirty tree**: $(supervisor_dirty_state)
- **INBOX count**: $(inbox_actionable_count) item(s)
- **INBOX items**: $(inbox_actionable_items)
- **general handoffs pending**: $(general_actionable_count)
- **Aged tick branches (>24h)**: $(cd $SUPERVISOR && git for-each-ref --format='%(refname:short) %(committerdate:relative)' 'refs/heads/ticks/*' 2>/dev/null | awk '$0 ~ /day|week|month/ {print "  - "$0}' | head -5)

## Recent principal statements (last 48h from JSONL)

_Parsed from user turns; helps sessions avoid re-asking or reversing principal statements._

$(python3 $SUPERVISOR/scripts/lib/verify-state-recent-turns.py)

---
_Regenerated: \`$SUPERVISOR/scripts/lib/verify-state.sh\`. If this file is older than 1h and you're about to make a principal-facing claim, re-run first._
PAID

exec 3>&-

if [[ $STDOUT -eq 1 ]]; then
  cat "$BUF"
else
  mv "$BUF" "$OUT"
  echo "wrote: $OUT"
fi
